In [3]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data = asarray([['bronze'], ['silver'], ['gold']])
print (data)

encoder = OrdinalEncoder()

result = encoder.fit_transform(data)
print(result)

[['bronze']
 ['silver']
 ['gold']]
[[0.]
 [2.]
 [1.]]


In [ ]:
# !pip install category_encoders

In [4]:
import pandas as pd
from pandas import DataFrame
df = pd.DataFrame({'Award':['Bronze', 'Silver', 'Gold']})
print(df)

    Award
0  Bronze
1  Silver
2    Gold


In [5]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [6]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(drop='first',sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]
